# Install the apt prerequisites
language: go

go:
  - master # This uses automatically the latest version of go

#install:
#  - go get github.com/spf13/hugo # This provides the latest version of Hugo to Travis CI

script:
  - bin/hugo

    # Deploy to GitHub pages
deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  repo: opentechinstitute/opentechinstitute.github.io
  on:
    branch: master
